### ISSUE TITLE
Pit Panel

### ISSUE THREAD

**Issue by andrewjong** [andrewjong/mancala-project#21]
Panel to hold stones. Possibly Grid Layout

**Comment by lokasplash** [comment]
Should pitpanel have a shape representing the pit itself?
We could delegate the contains() to the shape, giving us the ability to do pit bounds checking inside of the pitpanel.

In branch controller-pitpanel-playground, PitPanelControllerTest is a demo of having such a shape component inside pitpanel and a corresponding mouselistener.

branch controller-pitpanel-playground is based on (8d81a7b) of this issue's branch and an "advance testing" version of controller.java. The listener names inside of this controller.java are placeholders, not finalized.

**Comment by andrewjong** [comment]
I think it's a good idea.

Did you change JUnit5 to JUnit4 by the way? Tests no longer compile on my machine, am guessing this is the reason.

**Comment by lokasplash** [comment]
oops, I included a version of BoardModelTest.java that isn't Junit5 and not Junit4 either.
I think if you make the commented imports uncommented and comment the current ones, as well as remove public qualifier from the class, it should work for Junit5

**Comment by andrewjong** [comment]
Cool, I just changed the imports locally and it worked as expected. I think the addition of shape for bounds in PitPanel works really well as demonstrated in the test method.

I think it's a good idea to refactor the test methods out of the source classes to separate test classes in the tests/ folder. I just pushed edits and opened a pull-request from my branch that has the refactoring to controller-pitpanel-playground branch. Can you review and accept merge if you approve? Then we can make a pull-request from there to master.

**Comment by andrewjong** [comment]
Also, remember to comment/document methods as we go along  We'll have to turn in a javadoc for the project.
