### ISSUE TITLE
Grid Panel

### ISSUE THREAD

**Issue by premboy** [andrewjong/mancala-project#22]
create grid panel that shows pitpanels

**Comment by premboy** [comment]
grid panel
array of panels (player 1 and player2) for constructor
6x2
add new Controller.pitpanellistener(player side, index, panel.getshape)

**Comment by premboy** [comment]
wait was pitpanellistener ever pushed to master?

**Comment by lokasplash** [comment]
pitpanellistener is under Controller.java
